name: "Terraform Destroy"

on:
  push:
    branches:
      - staging
  workflow_dispatch:
jobs:
  terraform:
   name: "Terraform Destroy env"
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   steps:
   - name: Get code
     uses: actions/checkout@v3

   - name: Setup Terraform CLI
     uses: hashicorp/setup-terraform@v2 
  
   - name: init and  destroy
     run: |
          terraform init
          terraform destroy -var 'private_key_path=/home/runner/work/dev-env-aws-cicd/dev-env-aws-cicd/private_key.pem' --auto-approve 